# Generated by Django 2.2 on 2020-05-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Datos de Usuario', 'verbose_name_plural': 'Información'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidades del Usuario', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Perfiles'},
        ),
    ]
