# Generated by Django 2.2 on 2020-05-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200507_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detaroles',
            options={'verbose_name': 'Roles de Usuario', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Calaficacion del usuario', 'verbose_name_plural': 'Competencias'},
        ),
    ]
