# Generated by Django 2.2 on 2020-05-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200507_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Calaficacion del usuario', 'verbose_name_plural': 'Calificaciones'},
        ),
    ]
