# Generated by Django 2.2 on 2020-05-13 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20200507_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosuser',
            name='adddata',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fue creado el'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='apelUser',
            field=models.CharField(max_length=236, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='geneUser',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='modifiat',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Genero modificado'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='nombUser',
            field=models.CharField(max_length=236, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='teleUser',
            field=models.CharField(max_length=255, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='userDNI',
            field=models.CharField(max_length=25, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='estadoRol',
            field=models.CharField(max_length=19, verbose_name='Estado del rol'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificación del usuario'),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='DescHabil',
            field=models.TextField(max_length=2000, verbose_name='Descripción de la habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='idHabil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.habilidades', verbose_name='Identificador de habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de usuario'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='RoleName',
            field=models.CharField(max_length=50, verbose_name='Nombre del rol'),
        ),
    ]
