# Generated by Django 2.2 on 2020-05-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_auto_20200514_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='categproye',
            name='nombcate',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo de proyecto'),
        ),
    ]
